version: '3.3'
services:
  mysql-docker-container:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_deloitte
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
  test-deloitte:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: test-deloitte
    ports:
      - "8080:8080"
    container_name: test-deloitte
    depends_on:
      - mysql-docker-container